# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/MilimNavaDemonLord/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations
# you can use rvmm-config-gen to generate a config
# enabled = true/false

enable-magisk-update = true
parallel-jobs = 1
compression-level = 9
remove-rv-integrations-checks = true

patches-source = "anddea/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"

patches-version = "dev"
cli-version = "dev"

[YouTube]
enabled = true
build-mode = "both"
included-patches = "'Custom header for YouTube' 'Swipe controls'"
excluded-patches = "'Alternative thumbnails' 'Custom Shorts action buttons' 'Disable splash animation' 'Enable gradient loading screen' 'Force player buttons background' 'Hide action buttons' 'Hide feed components' 'Hide feed flyout menu' 'Hook download actions' 'Shorts components' 'Theme'"
version = "auto"
patcher-args = "-e 'Custom branding icon for YouTube' -OappIcon='revancify_red'"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music]
enabled = true
build-mode = "both"
arch = "both"
included-patches = "'Custom header for YouTube Music' 'Disable music video in album' 'Hide overlay filter' 'Hide player overlay filter'"
excluded-patches = "'Dark theme'"
version = "auto"
patcher-args = "-e 'Custom branding icon for YouTube Music' -OappIcon='revancify_red'"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

[GooglePhotos]
enabled = false
build-mode = "both"
arch = "both"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

[Spotify]
enabled = true
app-name = "Spotify"
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Reddit]
enabled = false
build-mode = "apk"
arch = "arm64-v8a"
version = "auto"
uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
uptodown-dlurl = "https://twitch.en.uptodown.com/android"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/tv.twitch.android.app"

[Twitter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
build-mode = "apk"
dpi = "120-640dpi"
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.twitter.android"

[TikTok]
enabled = false
# archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.zhiliaoapp.musically"
included-patches = "'SIM spoof'"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
arch = "arm64-v8a"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"
